name: medsam
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - setuptools
  - wheel
  - zlib
  - xz
  - tk
  - torchvision
  - transformers
  - sqlite
  - openssl
  - libffi
  - pyarrow   # Use an earlier version of pyarrow to avoid the DLL issue
  - zlib    # Specify a compatible version of zlib
  - libarrow
  - pip:
      - aiohappyeyeballs==2.4.4
      - aiohttp==3.11.11
      - aiosignal==1.3.2
      - anyio==4.6.2.post1
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - asttokens==2.4.1
      - async-lru==2.0.4
      - async-timeout==5.0.1
      - attrs==24.2.0
      - babel==2.16.0
      - beautifulsoup4==4.12.3
      - bleach==6.1.0
      - certifi==2024.8.30
      - cffi==1.17.1
      - charset-normalizer==3.4.0
      - comm==0.2.2
      - contourpy==1.3.0
      - cycler==0.12.1
      - datasets==3.2.0
      - debugpy==1.8.7
      - decorator==5.1.1
      - defusedxml==0.7.1
      - dill==0.3.8
      - exceptiongroup==1.2.2
      - executing==2.1.0
      - fastjsonschema==2.20.0
      - filelock==3.16.1
      - fonttools==4.54.1
      - fqdn==1.5.1
      - frozenlist==1.5.0
      - fsspec==2024.9.0
      - git+https://github.com/facebookresearch/segment-anything.git
      - git+https://github.com/huggingface/transformers.git
      - h11==0.14.0
      - httpcore==1.0.6
      - httpx==0.27.2
      - huggingface-hub==0.27.1
      - idna==3.10
      - imageio==2.36.0
      - importlib-resources==6.4.5
      - ipython-genutils==0.2.0
      - jedi==0.19.1
      - jinja2==3.1.4
      - json5==0.9.25
      - jsonpointer==3.0.0
      - jsonschema-specifications==2024.10.1
      - jupyter-client==8.6.3
      - jupyter-core==5.7.2
      - jupyter-server-terminals==0.5.3
      - jupyterlab-pygments==0.3.0
      - jupyterlab-widgets==3.0.13
      - kiwisolver==1.4.7
      - lazy-loader==0.4
      - markupsafe==3.0.2
      - matplotlib==3.9.2
      - matplotlib-inline==0.1.7
      - mistune==3.0.2
      - monai==1.4.0
      - mpmath==1.3.0
      - multidict==6.1.0
      - multiprocess==0.70.16
      - nest-asyncio==1.6.0
      - networkx==3.4.2
      - nibabel==5.3.2
      - numpy==1.26.4
      - opencv-python==4.10.0.84
      - overrides==7.7.0
      - packaging==24.1
      - pandas==2.2.3
      - pandocfilters==1.5.1
      - parso==0.8.4
      - patchify==0.2.3
      - pexpect==4.9.0
      - pillow==11.0.0
      - platformdirs==4.3.6
      - prometheus-client==0.21.0
      - prompt-toolkit==3.0.48
      - propcache==0.2.1
      - psutil==6.1.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pyarrow==18.1.0
      - pycparser==2.22
      - pygments==2.18.0
      - pyparsing==3.2.0
      - python-dateutil==2.9.0.post0
      - python-json-logger==2.0.7
      - pytz==2024.2
      - pyyaml==6.0.2
      - pyzmq==26.2.0
      - referencing==0.35.1
      - regex==2024.11.6
      - requests==2.32.3
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rpds-py==0.20.0
      - safetensors==0.5.0
      - scikit-image==0.24.0
      - scipy==1.14.1
      - send2trash==1.8.3
      - simpleitk==2.4.0
      - six==1.16.0
      - sniffio==1.3.1
      - soupsieve==2.6
      - stack-data==0.6.3
      - sympy==1.13.1
      - terminado==0.18.1
      - tifffile==2024.9.20
      - tinycss2==1.3.0
      #- tokenizers==0.13.3  # Updated tokenizers version
      - torchaudio
      - tomli==2.0.2
  - pytorch
